// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/flyer/BcardBack.tsx": () => import("../components/mockups/flyer/BcardBack.tsx"),
  "./components/mockups/flyer/BcardFront.tsx": () => import("../components/mockups/flyer/BcardFront.tsx"),
  "./components/mockups/flyer/CoachFlyer.tsx": () => import("../components/mockups/flyer/CoachFlyer.tsx")
};
