// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/AppStore/Screenshot1_Scorekeeper.tsx": () => import("../components/mockups/AppStore/Screenshot1_Scorekeeper.tsx"),
  "./components/mockups/AppStore/Screenshot2_Stats.tsx": () => import("../components/mockups/AppStore/Screenshot2_Stats.tsx"),
  "./components/mockups/AppStore/Screenshot3_GameFilm.tsx": () => import("../components/mockups/AppStore/Screenshot3_GameFilm.tsx"),
  "./components/mockups/AppStore/Screenshot4_Highlights.tsx": () => import("../components/mockups/AppStore/Screenshot4_Highlights.tsx"),
  "./components/mockups/AppStore/Screenshot5_Paywall.tsx": () => import("../components/mockups/AppStore/Screenshot5_Paywall.tsx"),
  "./components/mockups/flyer/BcardBack.tsx": () => import("../components/mockups/flyer/BcardBack.tsx"),
  "./components/mockups/flyer/BcardFront.tsx": () => import("../components/mockups/flyer/BcardFront.tsx"),
  "./components/mockups/flyer/CoachFlyer.tsx": () => import("../components/mockups/flyer/CoachFlyer.tsx"),
  "./components/mockups/flyer/PrintSheet.tsx": () => import("../components/mockups/flyer/PrintSheet.tsx")
};
